version: '3'
services:
  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.15.0
    ports:
      - 2181:2181
  kafka:
    image: eventuateio/eventuateio-local-kafka:0.15.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181
  mysql:
    image: eventuateio/eventuate-tram-sagas-mysql:0.3.0.RELEASE
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  tram-cdc-service:
    image: eventuateio/eventuate-tram-cdc-mysql-service:0.3.0.RELEASE
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890
      EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME: message
  ftgo-order-service:
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - kafka
      - tram-cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      JAVA_OPTS: -Xmx256m
