version:               2
jobs:
  build:
    machine:           true
    working_directory: ~/ftgo-application
    steps:
      - checkout
      - restore_cache:
          keys:
            - ftgo-application-{{ checksum "gradle.properties" }}
            - ftgo-application-
      - run:           TERM=dumb ./build-contracts.sh
      - run:           TERM=dumb ./gradlew testClasses :ftgo-order-service:compileComponentTestJava
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key:         ftgo-application-{{ checksum "gradle.properties" }}
      - run:
          command:     |
            ./.circleci/upgrade-docker-compose.sh
            . ./setenv-circle-ci.sh
            ./build-and-test-all.sh
      - run:
          name:        Save test results
          command:     |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when:        always
      - store_test_results:
          path:        ~/junit
      - store_artifacts:
          path:        ~/junit
      - run:
          command:     |
            . ./setenv-circle-ci.sh
            ./gradlew assemble
            docker-compose build
            ./publish-docker-images.sh
