apiVersion: v1
kind: Service
metadata:
  name: ftgo-dynamodb-local
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    svc: ftgo-dynamodb-local
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ftgo-dynamodb-local
  labels:
    application: ftgo
spec:
  serviceName: "ftgo-dynamodb"
  replicas: 1
  template:
    metadata:
      labels:
        svc: ftgo-dynamodb-local
    spec:
      containers:
      - name: ftgo-dynamodb-local
        image: cnadiminti/dynamodb-local:2017-04-22_beta
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
          - name: ftgo-dynamodb-persistent-storage
            mountPath: /dynamodb_local_db
  volumeClaimTemplates:
  - metadata:
      name: ftgo-dynamodb-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ftgo-dynamodb-local-init
spec:
  template:
    spec:
      containers:
      - name: ftgo-dynamodb-local-init
        image: msapatterns/dynamodblocal-init
        env:
          - name: AWS_DYNAMODB_ENDPOINT_URL
            value: http://ftgo-dynamodb-local:8000
          - name: AWS_ACCESS_KEY_ID
            value: FOO_ID
          - name: AWS_SECRET_ACCESS_KEY
            value: FOO_SECRET
      restartPolicy: Never
---
