apiVersion: v1
kind: Service
metadata:
  name: ftgo-zookeeper
  labels:
    name: ftgo-zookeeper
spec:
  ports:
  - port: 2181
    targetPort: 2181
  clusterIP: None
  selector:
    role: ftgo-zookeeper
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ftgo-zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        role: ftgo-zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ftgo-zookeeper
          image: confluentinc/cp-zookeeper:5.2.4
          ports:
              - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
          volumeMounts:
            - name: ftgo-zookeeper-persistent-storage
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: ftgo-zookeeper-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
